# Project: WordCount
# Makefile created by Dev-C++ 5.6.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = bin/WordCount_private.res
OBJ      = bin/main.o bin/ccount.o $(RES)
LINKOBJ  = bin/main.o bin/ccount.o $(RES)
LIBS     = -L"C:/Users/pbalduino/Applications/Dev-Cpp/MinGW32/lib" -L"C:/Users/pbalduino/Applications/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"C:/Users/pbalduino/Applications/Dev-Cpp/MinGW32/include" -I"C:/Users/pbalduino/Applications/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/pbalduino/Applications/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/projetos/anhanguera/3 semestre/pe2/CodeCount/src/include"
CXXINCS  = -I"C:/Users/pbalduino/Applications/Dev-Cpp/MinGW32/include" -I"C:/Users/pbalduino/Applications/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/pbalduino/Applications/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Users/pbalduino/Applications/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++" -I"C:/projetos/anhanguera/3 semestre/pe2/CodeCount/src/include"
BIN      = bin/WordCount.exe
CXXFLAGS = $(CXXINCS) -fsyntax-only -Wfatal-errors
CFLAGS   = $(INCS) -fsyntax-only -Wfatal-errors
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

bin/main.o: src/main.c
	$(CC) -c src/main.c -o bin/main.o $(CFLAGS)

bin/ccount.o: src/ccount.c
	$(CC) -c src/ccount.c -o bin/ccount.o $(CFLAGS)

bin/WordCount_private.res: WordCount_private.rc 
	$(WINDRES) -i WordCount_private.rc --input-format=rc -o bin/WordCount_private.res -O coff 
